### ISSUE TITLE
Should I add contributing.md to it

### ISSUE THREAD

**Issue by Sloth-Panda** [smaranjitghose/img_ai_app_boilerplate#19]
I can't see any contributing.md so Should I make that

**Comment by Sloth-Panda** [comment]
If required plz let me know

**Comment by smaranjitghose** [comment]
> I can't see any contributing.md so Should I make that

Sure. You can take it from my other projects like doc2pen

**Comment by Sloth-Panda** [comment]
ok ok will do that

**Comment by Sloth-Panda** [comment]
Hey, have made the PR and did the required changes. Kindly check it out and revert if any other changes are required. also plz attach a label to it.

**Comment by smaranjitghose** [comment]
> Hey, have made the PR and did the required changes. Kindly check it out and revert if any other changes are required. also plz attach a label to it.

Don't worry. I'll definitely check out the PRs once you are assigned. 😉
I would request you refrain from putting these additional messages on the issues as I get additional notifications. You can tag me over slack or on the PR itself for it.
I hope you understand
