### ISSUE TITLE
Write a guide for deploying the app to Linode 🐱‍💻

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/img_ai_app_boilerplate#25]
- Please name it `Linode_Guide.MD`
- Place it inside the `Guides/` directory of the master branch
- Have a look at the other guides and elaborately describe the process ( It would be appreciated if the process of registration is also highlighted but optional)
- Add Snapshots of the process as and where required
- Add `Useful Tips` section for certain optimizations, bug fixing advice and cite corresponding references

**Comment by pratik-choudhari** [comment]
@smaranjitghose I would like to work on this

**Comment by smaranjitghose** [comment]
> @smaranjitghose I would like to work on this

Assigned for 2 days

**Comment by pratik-choudhari** [comment]
Hey @smaranjitghose , added the MD file to PR #51
