### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [smaranjitghose/img_ai_app_boilerplate#38]
Hi @smaranjitghose 
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
Kindly do assign me this issue @smaranjitghose 
( config file having a proper message)

For reference, kindly check out: https://github.com/apps/welcome

**Comment by smaranjitghose** [comment]
This is not required as of now
