### ISSUE TITLE
Add Contributors Table in README.md File

### ISSUE THREAD

**Issue by samir-0711** [smaranjitghose/img_ai_app_boilerplate#45]
Like this
![image](https://user-images.githubusercontent.com/68433936/104679457-bc4ba000-5713-11eb-840f-6b1929ad6b83.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by smaranjitghose** [comment]
Please use the one as shown [here](https://github.com/smaranjitghose/awesome-portfolio-websites/tree/master)

**Comment by smaranjitghose** [comment]
This is not a big project and the above stated feature is hence not required at this stage
