### ISSUE TITLE
Edit from Github Links are not working.

### ISSUE THREAD

**Issue by raman08** [smaranjitghose/img_ai_app_boilerplate#49]
When we go to the Edit on GitHub on any documentation page, It will redirect us to the wrong page.
![Screenshot from 2021-01-16 16-00-43](https://user-images.githubusercontent.com/56781806/104809534-02882880-5814-11eb-8474-353a8b800752.png)

**Comment by smaranjitghose** [comment]
Ya, I have seen this before. Actually, that option is only for people having a collaborator access
