### ISSUE TITLE
Guide for Deployment to AWS

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/img_ai_app_boilerplate#5]

**Comment by thesauravkarmakar** [comment]
Will Elastic Beanstalk Deployment work?

**Comment by smaranjitghose** [comment]
> Will Elastic Beanstalk Deployment work?

Ya, you can write a guide for that

**Comment by thesauravkarmakar** [comment]
> > Will Elastic Beanstalk Deployment work?
> 
> Ya, you can write a guide for that

Okay! Then I can do that
