### ISSUE TITLE
 Add Multiple Pages  

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/img_ai_app_boilerplate#9]
- [x] Contact Page  
- [x] About Page  
- [x] Feedback Page

**Comment by ThenoobMario** [comment]
Hey, can you elaborate on this? Like what exactly do you want to be done in this issue.

**Comment by smaranjitghose** [comment]
> Hey, can you elaborate on this? Like what exactly do you want to be done in this issue.

Sure, the current streamlit app has only a home page that loads by default and a contact page. For a prototype, we usually need more pages including contact, about, support, etc

**Comment by ThenoobMario** [comment]
Okay so we need to add those pages along with some general text that users can use, right?

Edit: I figured it out 😄

**Comment by ThenoobMario** [comment]
Hey, I am trying to make a feedback form for the feedback page which would implement sending a feedback email. Should I implement it using flask? Or like do you have any suggestion as to how should I go about it?

**Comment by smaranjitghose** [comment]
> Hey, I am trying to make a feedback form for the feedback page which would implement sending a feedback email. Should I implement it using flask? Or like do you have any suggestion as to how should I go about it?

We are already using streamlit for this. Please have a look at the readme and the codebase

**Comment by ThenoobMario** [comment]
> > Hey, I am trying to make a feedback form for the feedback page which would implement sending a feedback email. Should I implement it using flask? Or like do you have any suggestion as to how should I go about it?
> 
> We are already using streamlit for this. Please have a look at the readme and the codebase

Alright I'll go through the documentation again
